version: 2
project_name: mdcmux
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go vet ./...
    - go tool honnef.co/go/tools/cmd/staticcheck ./...
    - go tool github.com/google/addlicense -c "Bob Vawter (bob@vawter.org)" -l mit -s -check -ignore '**/*.xml'  -ignore '**/*.yaml' -ignore 'Dockerfile' .

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

kos:
  - repositories:
      - "bobvawter/mdcmux"
      - "ghcr.io/bobvawter/mdcmux"
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - formats: [ tar.gz ]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [ zip ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
